### ISSUE TITLE
Menu glitch

### ISSUE THREAD

**Issue by rayman89** [andy-portmen/undo-closed-tabs-button#11]
Setting remember history for 21+ history makes the menu starts to have problems. FOr example at 21 "Clear history" disappears 22 makes "Show full tab history" disappear and so on. Seems like the menu can't make itself bigger than 20 items. Probably a scroll bar should be added to be able to display more than 20 items.

**Comment by andy-portmen** [comment]
Thanks for the report. It is fixed in the latest release.

**Comment by rayman89** [comment]
Thank you for the update. Seems like "Show full tab history" was removed was that intentional?

![imagen](https://user-images.githubusercontent.com/5449042/34787617-7e75b6d2-f5fd-11e7-9fff-7d34aab8ee23.png)
