### ISSUE TITLE
Firefox 57 compatibility

### ISSUE THREAD

**Issue by ygoe** [andy-portmen/undo-closed-tabs-button#5]
This add-on is marked incompatible with Firefox 57. If this isn't changed, this addon will be useless in a month. Which would be very unfortunate because I really like it. It happens too often that a tab was accidently closed because the mouse cursor was moving in strange ways or the tabs were moving beneath the cursor. It's good to have that tab with its full state, including the history, available.

Alternatively, are there any other addons that do the same in Firefox 57? Most addons I've found for Chrome a few years ago just re-opened the last URL of a tab, but didn't restore their history. Firefox can do that alone.

**Comment by andy-portmen** [comment]
https://addons.mozilla.org/en-US/firefox/addon/undo-closed-tabs-revived/

**Comment by ygoe** [comment]
@andy-portmen That add-on cannot be downloaded, says my browser. Some error. Maybe on Mozilla's side.

**Comment by jaegerschnitzel** [comment]
The new add-on is missing a lot of features and has a really bad user experience.
Can you please update the new add-on that i thas the same features as the non web extension version?

**Comment by ygoe** [comment]
From what I know, Firefox 57 has dropped the required features for this on the Web Extension API level. So there's nothing to do. This add-on just became impossible to make. No other browser can do it either. Pretty new world.

**Comment by andy-portmen** [comment]
What are the main features that you need which are not present?

**Comment by asc7uni** [comment]
Hello.
For me most desired but missing features in new add-on are:
- Gray icon
- Two separate areas on button. One for restore last closed tab and other is drop-down list.
- Ability to clear closed tabs history

**Comment by andy-portmen** [comment]
> Gray icon

0.1.3 has a gray color.

> Two separate areas on button

Not doable in the WebExtension context

> Ability to clear closed tabs history

This is available in 0.1.3

**Comment by jaegerschnitzel** [comment]
Thanks for 0.1.4. I'm also missing the two separate areas.
Maybe it's possible to add an option which changes the default behaviour. Left click restores last closed tab and right click shows drop-down list?
