### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by rayman89** [andy-portmen/undo-closed-tabs-button#6]
On the pictures you did put on AMO for Undo Closed Tabs Button (revived)  it shows favicons but I'm not able to see the favicons.

BTW could you explain me how there are some closed tabs that have an icon to open them in an other window. Are those closed windows or just closed tabs from an other window other than the current one?

**Comment by andy-portmen** [comment]
> On the pictures you did put on AMO for Undo Closed Tabs Button (revived) it shows favicons but I'm not able to see the favicons.

It is fixed now using a Google service to get favicons (there is no API yet to get favicons locally in Firefox)

> BTW could you explain me how there are some closed tabs that have an icon to open them in an other window. Are those closed windows or just closed tabs from an other window other than the current one?

If a window get closed you will get that icon. Pressing the icon restores the window as well as all its tabs.
